site_name: RenderCV Engine
site_description: Write your CV or resume as YAML and get a beautiful PDFâ€”built for academics and engineers.
repo_url: https://github.com/rendercv/rendercv
repo_name: rendercv/rendercv
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/images/icon.svg
  language: en
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - content.code.copy # the copy-to-clipboard buttons for code blocks
    - content.action.view # view source button for pages
    - content.action.edit # view source button for pages
    - navigation.footer # the previous and next buttons in the footer
    - navigation.tabs # Top navbar
    - navigation.indexes # allow mother pages to have their own index pages
    - navigation.instant # instant navigation for faster page loads
    - navigation.instant.prefetch # prefetch pages for instant navigation
    - navigation.instant.progress # show progress bar for instant navigation
    - navigation.top # back to top button
    - navigation.sections # make sidebar expanded by default
    - search.highlight # highlight search results after going to a page
    - search.suggest # show search suggestions while typing
    - search.share # share search results with others
    - toc.follow # if toc sidebar doesn't fit, scroll to the active heading
    - content.code.annotate # allow annotations in code blocks
    - content.tabs.link # switch all the content tabs to the same label

nav:
  - Getting Started:
      - Welcome: user_guide/welcome_to_rendercv.md
      - Quick Start: user_guide/get_started.md
      - YAML Input Structure: user_guide/structure_of_the_yaml_input_file.md
      - CLI Reference: user_guide/cli_reference.md
      - FAQ: user_guide/faq.md
  - Developer Guide:
      - Introduction: developer_guide/get_started.md
      - Architecture: developer_guide/architecture.md
      - Code Guidelines: developer_guide/code_guidelines.md
      - Running Tests: developer_guide/testing.md
      - Writing Tests: developer_guide/writing_tests.md
      - Writing Documentation: developer_guide/writing_documentation.md
      - Releasing: developer_guide/releasing.md
      - Scripts: developer_guide/scripts.md
      - CI/CD Workflows: developer_guide/workflows.md
      - How-To Guides:
          - Add a New Entry Type: how_to/add_a_new_entry_type.md
          - Add a New Theme: how_to/add_a_new_theme.md
          - Add a New Locale: how_to/add_a_new_locale.md
          - Add a New Social Network: how_to/add_a_new_social_network.md
  - API Reference: api_reference/
  - Changelog: changelog.md

markdown_extensions:
  # see https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/ for more pymdownx info
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # content tabs
      alternate_style: true
  - toc:
      permalink: true
      title: Page contents
  - admonition # blocks like note, warning, tip, etc.

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - gen-files:
      scripts:
        - docs/api_reference/api_reference.py
  # - macros: # mkdocs-macros-plugin
  #     module_name: docs/dynamic_content_generation
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_bases: true
            docstring_section_style: list
            docstring_style: google
            inherited_members: true
            show_root_heading: true
            heading_level: 1
            show_symbol_type_heading: True
            show_root_full_path: false
            show_symbol_type_toc: true
            signature_crossrefs: true
            show_docstring_attributes: true
            show_source: true
            show_submodules: false
            merge_init_into_class: true
            annotations_path: "source"
            show_signature: false
            show_docstring_examples: true
            show_docstring_functions: true
            show_signature_annotations: false
            show_docstring_type_aliases: true
            show_overloads: false

extra_javascript:
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - assets/stylesheets/rendercv.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  analytics:
    provider: google
    property: G-7D7Y8D5Q4W
  social:
    - icon: material/github
      link: https://github.com/rendercv
    - icon: material/linkedin
      link: https://www.linkedin.com/company/rendercv/
