name: Publish a release

# GitHub events that trigger the workflow:
on:
  release:
    types:
      - published
jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yaml

  update_files:
    name: Update schema.json, examples, and entry figures
    uses: ./.github/workflows/update-files.yaml
    needs:
      - test