name: Update files

# GitHub events that trigger the workflow:
on:
  workflow_call: # to make the workflow triggerable from other workflows (publish-a-release.yaml)
  workflow_dispatch: # to make the workflow triggerable manually

jobs:
  update_files:
    name: Update schema.json, examples, and entry figures
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Set Git credentials
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions [Bot]"

      - name: Update schema.json
        continue-on-error: true
        run: |
          just update-schema
          git add schema.json

      - name: Update `examples` folder
        continue-on-error: true
        run: |
          just update-examples
          git add examples/*
          git add docs/assets/images/*.png

      - name: Update entry figures
        continue-on-error: true
        run: |
          just update-entry-figures
          git add docs/assets/images/**/*.png

      - name: Push changes
        continue-on-error: true
        run: |
          git commit -m "Update schema.json, examples, and entry figures"
          git push origin HEAD:main
